const CREATE_STATUS_CODE = 201
const SUCCESS_STATUS_CODE = 200
const ERROR_STATUS_CODE = 400
const UNAUTHORIZATION_CODE=401
const FORBIDDEN_STATUS_CODE=403
const NOT_FOUND_STATUS_CODE = 404
const SERVER_ERROR_STATUS_CODE = 500

module.exports = {
    CREATE_STATUS_CODE,
    SUCCESS_STATUS_CODE,
    ERROR_STATUS_CODE,
    NOT_FOUND_STATUS_CODE,
    SERVER_ERROR_STATUS_CODE,
    UNAUTHORIZATION_CODE,
    FORBIDDEN_STATUS_CODE
}